// ============================================================================
// Runtime loader for the structured ACC price-table data generated by
// scripts/ingest-acc-schedules.mjs. Shipped as a plain JSON asset under
// public/data/acc/schedules.json and fetched at runtime — NOT `import`ed as a
// JS module, because the full parsed elective-surgery subset alone is over
// 300KB (long real procedure descriptions) and this app's single-file build
// (`vite-plugin-singlefile`) would otherwise inline all of that into the one
// shipped index.html every session needs to parse/execute, whether or not
// that session ever opens Contracts. Same "large local asset, not inlined"
// precedent as knowledgeCorpus.ts / scripts/copy-tesseract-assets.mjs.
// ============================================================================

import type { CotrRateItem, ScheduleItem } from './scheduleParser';
import type { ParsedScheduleFile } from './nationalContracts';

interface SchedulesFile {
  generatedAt: string;
  schedules: { sourceDocId: string; items: (ScheduleItem | CotrRateItem)[] }[];
}

let cached: ParsedScheduleFile[] | null = null;

/** Fetches (and caches) the generated structured schedule data. Returns `[]` (never throws) if the asset is missing/unfetchable. */
export async function loadAccScheduleData(): Promise<ParsedScheduleFile[]> {
  if (cached) return cached;
  try {
    const res = await fetch('/data/acc/schedules.json');
    if (!res.ok) return [];
    const file = (await res.json()) as SchedulesFile;
    cached = (file.schedules ?? []) as ParsedScheduleFile[];
    return cached;
  } catch {
    return [];
  }
}

/** Test-only hook to reset the module-level cache between test files. */
export function _resetAccScheduleDataCacheForTests(): void {
  cached = null;
}
